### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sbromberger** [kho/probing#1]
Hi,

I've made a concrete implementation of a linear probing hashmap based off this template and was wondering what the license was. Could you let me know?

Thanks.

**Comment by kho** [comment]
I wasn't expecting that someone would actually use the code I wrote back in grad school! That's such a compliment. And thank you for asking about licensing!

Please consider the code in this repository to be in the public domain and use them however you like.

**Comment by kho** [comment]
Updated README.md to state so.
